const express = require('express');
const { loadGuestBook } = require('./app/handlers/loadGuessBook.js');
const { logRequest } = require('./app/handlers/logRequest.js');
const { serveGuestBook, addComment } = require('./app/handlers/guestBookHandler.js');
const { serveComments } = require('./app/handlers/apiHandler.js');
const { injectCookies } = require('./app/handlers/injectCookies.js');
const { injectSession } = require('./app/handlers/injectSession.js');
const { signUp, serveSignUpForm } = require('./app/handlers/signup.js');
const { login, serveLoginForm } = require('./app/handlers/loginHandler.js');
const { loadUserDetails } = require('./app/handlers/loadUserDetails.js');
const { logout } = require('./app/handlers/logout.js');
const { notFound } = require('./app/handlers/notFound.js');
const dataFile = './data/guestBook.json';
const guestBookTemplate = './src/app/template/guestBook.html';
const loginFormTemplate = './src/app/template/login.html';
const singUpTemplate = './src/app/template/signup.html';
const commentsFile = './data/guestBook.json';
const userDetailsFile = './data/userDetails.json';

const createApp = (appConfig, sessions) => {
  const app = express();
  const parseBodyParams = express.urlencoded({ extended: true });
  app.use(loadUserDetails(userDetailsFile));
  app.use(logRequest);
  app.use(parseBodyParams);
  app.use(injectCookies);
  app.use(injectSession(sessions));
  app.get('/guest-book', loadGuestBook(commentsFile), serveGuestBook(guestBookTemplate));
  app.post('/guest-book', loadGuestBook(commentsFile), addComment);
  app.get('/api/comments', serveComments(dataFile));
  app.get('/login', serveLoginForm(loginFormTemplate));
  app.post('/login', login(sessions));
  app.get('/sign-up', serveSignUpForm(singUpTemplate));
  app.post('/sign-up', signUp);
  app.get('/logout', logout(sessions));
  app.use(express.static(appConfig.staticDir));
  app.use(notFound);
  return app;
};

module.exports = { createApp };
