name: CI
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building application"

  approve-and-deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: approval
    steps:
      - run: echo "Running when manually triggered"
