name: CI
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building application"

  approve-and-deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: approval
    steps:
      - run: |
          echo "Copying file"
          touch temp
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          mkdir ~/.ssh
          ssh-keyscan -H 10.131.132.34 >> ~/.ssh/known_hosts
          scp -i private_key temp atul@10.131.132.34:/opt/fast/firmware
